version: "3.9"
networks:
  dnd-network:
    external: true
services:
  session-db:
    image: postgres:12-alpine
    container_name: session-db
    ports:
      - "5436:5432"
    networks:
      - dnd-network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=session-db

  dnd-session-service:
    image: eliriat/dnd-session-service
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dnd-session-service
    networks:
      - dnd-network
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://root:secret@session-db:5432/session-db?sslmode=disable
      - SERVER_ADDRESS=0.0.0.0:8082
    depends_on:
      - session-db
    restart: always
    ports:
      - "8082:8082"
    expose:
      - "8082"
    entrypoint:
      [
        "/app/wait-for.sh",
        "session-db:5432",
        "--",
        "/app/start.sh"
      ]
    command: ["/app/main"]