// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Session struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	CampaignID int64  `json:"campaignId"`
	MapID      int64  `json:"mapId"`
}

type SessionAllowedCharacter struct {
	SessionID   int64 `json:"sessionId"`
	CharacterID int64 `json:"characterId"`
}

type SessionCharactersPosition struct {
	SessionID        int64     `json:"sessionId"`
	CharID           int64     `json:"charId"`
	XPos             int32     `json:"xPos"`
	YPos             int32     `json:"yPos"`
	IsVisible        bool      `json:"isVisible"`
	ModificationDate time.Time `json:"modificationDate"`
}

type SessionObjectsPosition struct {
	SessionID        int64     `json:"sessionId"`
	ObjectID         int64     `json:"objectId"`
	XPos             int32     `json:"xPos"`
	YPos             int32     `json:"yPos"`
	IsVisible        bool      `json:"isVisible"`
	ModificationDate time.Time `json:"modificationDate"`
}
