// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Session struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	CampaignID int64  `json:"campaign_id"`
	MapID      int64  `json:"map_id"`
}

type SessionAllowedCharacter struct {
	SessionID   int64 `json:"session_id"`
	CharacterID int64 `json:"character_id"`
}

type SessionCharactersPosition struct {
	SessionID        int64     `json:"session_id"`
	CharID           int64     `json:"char_id"`
	XPos             int32     `json:"x_pos"`
	YPos             int32     `json:"y_pos"`
	IsVisible        bool      `json:"is_visible"`
	ModificationDate time.Time `json:"modification_date"`
}

type SessionObjectsPosition struct {
	SessionID        int64     `json:"session_id"`
	ObjectID         int64     `json:"object_id"`
	XPos             int32     `json:"x_pos"`
	YPos             int32     `json:"y_pos"`
	IsVisible        bool      `json:"is_visible"`
	ModificationDate time.Time `json:"modification_date"`
}
